import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

import { View } from '../../context/view.js';
import type { Event } from '../../event/index.js';
import { InMemoryFileStore } from '../../io/index.js';
import { EventLog } from '../event-log.js';
import { restoreConversationState } from '../restore.js';
import oracle from '../__fixtures__/python-condensation-wire-oracle.json';

type WireCase = (typeof oracle.cases)[number];

// Generated by real Python EventLog serialization/reopening and View replay.
describe('pinned Python condensation persistence oracle', () => {
  it('uses the canonical manifest pin', () => {
    const manifest = JSON.parse(readFileSync(new URL('../../../transpile/upstream.json', import.meta.url), 'utf8'));
    expect(oracle.upstream_commit).toBe(manifest.commit);
  });

  it.each(oracle.cases)('$name restores complete Python model JSON and persists canonical event records', (fixture) => {
    checkImportedRoundTrip(fixture.events, fixture);
  });

  it.each(oracle.cases)('$name restores Python persisted JSON with omitted optional fields', (fixture) => {
    checkImportedRoundTrip(fixture.files.map(file => file.event), fixture);
  });

  it.each(oracle.cases)('$name reopens Python event files and produces the same retained View', (fixture) => {
    const store = new InMemoryFileStore(Object.fromEntries(fixture.files.map(file => [
      file.path, JSON.stringify(portableWire(file.event)),
    ])));
    const events = new EventLog(store).toArray();
    expect(canonical(events)).toEqual(canonical(fixture.restored));
    checkView(events, fixture);
  });
});

function checkImportedRoundTrip(payload: unknown, fixture: WireCase): void {
  const imported = restoreConversationState(payload);
  expect(canonical(imported.state.events)).toEqual(canonical(fixture.restored));
  checkView(imported.state.events, fixture);

  const store = new InMemoryFileStore();
  new EventLog(store).appendMultiple(imported.state.events);
  const files = store.list('events').filter(path => path.endsWith('.json')).sort().map(path => ({
    path, event: JSON.parse(store.read(path)) as unknown,
  }));
  expect(canonical(files)).toEqual(canonical(fixture.files));
  const reopened = new EventLog(store).toArray();
  expect(canonical(reopened)).toEqual(canonical(fixture.restored));
  checkView(reopened, fixture);
}

function checkView(events: readonly Event[], fixture: WireCase): void {
  expect(events.filter(event => event.kind === 'ActionEvent' && event.action === null).map(event => event.id))
    .toEqual(fixture.null_action_ids);
  const before = canonical(events);
  const view = View.fromEvents(events);
  expect(canonical({
    events: view.events.map(event => {
      const value = { ...event } as Record<string, unknown>;
      // Synthesized summary timestamps are generated at replay time in both SDKs.
      delete value.timestamp;
      return value;
    }),
    unhandled_condensation_request: view.unhandledCondensationRequest,
    manipulation_indices: [...view.manipulationIndices].sort((left, right) => left - right),
  })).toEqual(canonical(fixture.view));
  expect(canonical(events)).toEqual(before);
}

/** DEV-SDK-001/002 omit action security metadata; no condensation field is omitted. */
function portableWire(value: unknown): unknown {
  if (!isRecord(value)) return value;
  const event = { ...value };
  if (event.kind === 'ActionEvent') {
    delete event.security_risk;
    delete event.critic_result;
    delete event.summary;
  }
  if (isRecord(event.tool_call)) {
    const call = { ...event.tool_call };
    delete call.security_risk;
    event.tool_call = call;
  }
  return event;
}

function canonical(value: unknown, key = ''): unknown {
  if (value instanceof Set) return [...value].sort();
  if (Array.isArray(value)) {
    const array = value.map(item => canonical(item));
    return key === 'forgotten_event_ids' ? array.sort() : array;
  }
  const portable = portableWire(value);
  if (!isRecord(portable)) return portable;
  return Object.fromEntries(Object.entries(portable)
    .filter(([, item]) => item !== null && item !== undefined)
    .map(([name, item]) => [name, canonical(item, name)]));
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
