#!/usr/bin/env python3
"""Regenerate limits and token goldens from the manifest-pinned SDK's uv.lock.

Requires the locked tiktoken version on PYTHONPATH and the locked LiteLLM sdist.
No provider calls or live conversations are used. The checked-in fixture's inputs
are the test cases; expected counts are recomputed by the original source functions.

python scripts/parity/generate-python-llm-budget-oracle.py --upstream SDK_CHECKOUT \
  --litellm-archive litellm-VERSION.tar.gz
"""
from __future__ import annotations
import argparse
import ast
import hashlib
import json
import subprocess
import tarfile
import tomllib
import types
import typing
from pathlib import Path
import tiktoken

PROVIDERS = {'openai', 'anthropic', 'gemini', 'deepseek', 'moonshot', 'minimax', 'mistral', 'xai', 'zai'}
FUNCTIONS = {'_count_messages', '_count_function_call_tokens', '_count_content_list', '_count_extra', '_format_function_definitions', '_format_object_parameters', '_format_type'}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--upstream', required=True, type=Path)
    parser.add_argument('--litellm-archive', required=True, type=Path)
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    pin = json.loads((root / 'transpile/upstream.json').read_text())['commit']
    head = subprocess.check_output(['git', '-C', str(args.upstream), 'rev-parse', 'HEAD'], text=True).strip()
    if head != pin:
        raise ValueError('Upstream checkout does not match canonical manifest pin')
    lock = tomllib.loads(subprocess.check_output(['git', '-C', str(args.upstream), 'show', f'{pin}:uv.lock'], text=True))
    litellm = next(package for package in lock['package'] if package['name'] == 'litellm')
    tokenizer = next(package for package in lock['package'] if package['name'] == 'tiktoken')
    if tiktoken.__version__ != tokenizer['version']:
        raise ValueError('Installed tiktoken does not match the pinned uv.lock')
    digest = hashlib.sha256(args.litellm_archive.read_bytes()).hexdigest()
    if 'sha256:' + digest != litellm['sdist']['hash']:
        raise ValueError('LiteLLM archive does not match the pinned uv.lock SHA256')
    prefix = f"litellm-{litellm['version']}/litellm/"
    with tarfile.open(args.litellm_archive) as archive:
        catalog = json.load(archive.extractfile(prefix + 'model_prices_and_context_window_backup.json'))
        source = archive.extractfile(prefix + 'litellm_core_utils/token_counter.py').read().decode()
    limits = {key: {'provider': value['litellm_provider'], 'maxInputTokens': value['max_input_tokens']}
              for key, value in catalog.items() if isinstance(value, dict)
              and value.get('litellm_provider') in PROVIDERS and value.get('mode') in ('chat', 'responses')
              and isinstance(value.get('max_input_tokens'), int) and value['max_input_tokens'] > 0}
    header = f"// Generated by scripts/parity/generate-python-llm-budget-oracle.py.\n// SDK pin {pin}; LiteLLM {litellm['version']} model_prices_and_context_window_backup.json.\n// Source sdist SHA256: {digest}\n// Model-level metadata, never a promise about custom proxy routes.\n"
    declaration = 'export const MODEL_INPUT_LIMITS: Readonly<Record<string, { readonly provider: string; readonly maxInputTokens: number }>> = {\n'
    (root / 'src/llm/model-input-limits.ts').write_text(header + declaration + ''.join(
        '  ' + json.dumps(key) + ': ' + json.dumps(value, separators=(',', ': ')) + ',\n'
        for key, value in sorted(limits.items())) + '};\n')
    code = 'from __future__ import annotations\n' + '\n\n'.join(
        ast.get_source_segment(source, node) for node in ast.parse(source).body
        if isinstance(node, ast.FunctionDef) and node.name in FUNCTIONS)
    namespace = dict(vars(typing))
    exec(compile(code, 'pinned-litellm-token-counter', 'exec'), namespace)
    path = root / 'src/llm/__tests__/fixtures/context-token-counts.json'
    cases = json.loads(path.read_text())['cases']
    for case in cases:
        # Explicit fixture encodings reproduce the locked generic fallback path.
        encoding = tiktoken.get_encoding('o200k_base' if case['model'] == 'gpt-4o' else 'cl100k_base')
        count = lambda text: len(encoding.encode(text, disallowed_special=()))
        old = case['model'] == 'gpt-3.5-turbo-0301'
        params = types.SimpleNamespace(tokens_per_message=4 if old else 3, tokens_per_name=-1 if old else 1, count_function=count)
        messages = json.loads(json.dumps(case['messages']))
        for message in messages:
            if message.get('tool_calls'):
                message['tool_calls'] = [{'id': call['id'], 'type': 'function', 'function': {'name': call['name'], 'arguments': call['arguments']}} for call in message['tool_calls']]
        case['expectedTokens'] = namespace['_count_messages'](params, messages, False, None) + namespace['_count_extra'](count, case['tools'], None, any(message['role'] == 'system' for message in messages))
    result = {'upstreamCommit': pin, 'source': f"LiteLLM {litellm['version']} litellm_core_utils/token_counter.py; original functions executed with tiktoken {tiktoken.__version__}", 'archiveSha256': digest, 'sourceSha256': hashlib.sha256(source.encode()).hexdigest(), 'cases': cases}
    path.write_text(json.dumps(result, indent=2, ensure_ascii=False) + '\n')
    print(f'Generated {len(limits)} model limits and {len(cases)} original-function token count fixtures')


if __name__ == '__main__':
    main()
